export const ActionTypes = {
  //start app
  START_APP: 'START_APP', 
  // add To Do
  ADD_TODO_REQUEST: 'ADD_TODO_REQUEST',
  ADD_TODO_SUCCESS: 'ADD_TODO_SUCESS',
  ADD_TODO_FAILURE: 'ADD_TODO_FAILURE',

  // remove To Do

  REMOVE_TODO_REQUEST: 'REMOVE_TODO_REQUEST',
  REMOVE_TODO_SUCCESS: 'REMOVE_TODO_SUCCESS',
  REMOVE_TODO_FAILURE: 'REMOVE_TODO_FAILURE',

  // add priority

  ADD_PRIORITY_REQUEST: 'ADD_PRIORITY_REQUEST',
  ADD_PRIORITY_SUCCESS: 'ADD_PRIORITY_SUCCESS',
  ADD_PRIORITY_FAILURE: 'ADD_PRIORITY_FAILURE',

  // remove priority

  REMOVE_PRIORITY_REQUEST: 'REMOVE_PRIORITY_REQUEST',
  REMOVE_PRIORITY_SUCCESS: 'REMOVE_PRIORITY_SUCCESS',
  REMOVE_PRIORITY_FAILURE: 'REMOVE_PRIORITY_FAILURE',

  //filter
  FILTER_ALL: 'FILTER_ALL',
  FILTER_PRIORITY: 'FILTER_PRIORITY'
}
